# Generated by Django 3.1 on 2020-08-17 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssebs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.FileField(upload_to='post/'),
        ),
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.AddField(
            model_name='notice',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssebs.post'),
        ),
    ]
