# Generated by Django 3.1 on 2020-08-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssebs', '0002_auto_20200817_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='post',
        ),
    ]
