# Generated by Django 3.1 on 2020-08-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssebs', '0003_remove_notice_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='body',
            field=models.FileField(null=True, upload_to='notice/'),
        ),
    ]
