# Generated by Django 3.1 on 2020-08-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssebs', '0004_notice_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.FileField(default='anything', upload_to='notice/'),
        ),
    ]
